"""Existing-state coverage across the 0.9.4.2 -> HEAD version boundary.

Class B root cause (Phase 0 RCA): the autouse ``_isolate_ironmesh_state``
fixture gives every test a pristine EMPTY ``~/.ironmesh``. Nothing exercised a
node with real accumulated state on disk, and two bugs shipped straight through
that hole with a green suite — the TOFU trust-store load and the ``doctor``
headless hang on ``audit.verify_chain``.

These tests point the CURRENT code at a **real** 0.9.4.2 golden fixture
(``tests/fixtures/existing_state/v0_9_4_2/``, written by the actual released
0.9.4.2 wheel — see ``generate_v0942_fixture.py``). That is the non-circular
complement to the two existing suites, which both build their "old" state with
HEAD's own code:

  * ``test_storage_kdf.py`` writes its "legacy" DB with HEAD's
    ``_derive_legacy_storage_key`` — it validates HEAD's *assumption* of the old
    format and would pass even if that assumption were wrong.
  * ``test_doctor_existing_state.py`` builds identity + audit chain with HEAD's
    ``generate_keypair`` / ``AuditLog`` — same circularity.

Here the artifacts were written by 0.9.4.2 itself, so a divergence between what
0.9.4.2 wrote and what HEAD expects is a real, caught failure. Every persisted-
state path Phase 0 flagged as uncovered gets an existing-state variant here,
headless and (where the resolution differs) interactive.
"""

import base64
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import aiosqlite
import pytest

import ironmesh

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "existing_state" / "v0_9_4_2"
MANIFEST = json.loads((FIXTURE_DIR / "manifest.json").read_text())
PP = MANIFEST["passphrase"]

# The golden fixture must be present and genuinely a 0.9.4.2 artifact. If it is
# ever regenerated by newer code this collection guard fails loudly rather than
# silently testing a HEAD-written DB.
pytestmark = pytest.mark.skipif(
    not (FIXTURE_DIR / "data.db").exists(),
    reason="golden 0.9.4.2 fixture missing",
)


@pytest.fixture
def golden_cfg(tmp_path):
    """A writable COPY of the golden 0.9.4.2 ``~/.ironmesh``.

    The checked-in fixture must never be mutated by a migrating open, so each
    test operates on a per-test copy. Returns the ``.ironmesh`` dir.
    """
    cfg = tmp_path / ".ironmesh"
    cfg.mkdir()
    for name in ("keys.json", "known_peers.json", "data.db", "audit.log"):
        shutil.copy(FIXTURE_DIR / name, cfg / name)
    return cfg


def _no_tty(monkeypatch):
    monkeypatch.setattr("ironmesh.cli_output.stdin_is_interactive", lambda: False)


def _clear_pp_env(monkeypatch):
    for var in ("IRONMESH_PASSPHRASE", "IRONMESH_KEYS_PASSPHRASE"):
        monkeypatch.delenv(var, raising=False)


# ---------------------------------------------------------------------------
# Fixture authenticity — proves we are testing a REAL old artifact
# ---------------------------------------------------------------------------

class TestFixtureIsGenuinelyLegacy:
    async def test_db_has_no_v2_prefix_and_no_salt(self):
        """The checked-in DB must be pre-v0.9.5 on disk: payloads carry no
        ``IMSTOREv2`` prefix and there is no persisted ``storage_salt``. This
        guards against the fixture being accidentally regenerated by current
        code (which would make every migration assertion below circular)."""
        from ironmesh.store import STORAGE_V2_MAGIC

        async with aiosqlite.connect(str(FIXTURE_DIR / "data.db")) as db:
            cur = await db.execute(
                "SELECT payload FROM messages WHERE payload IS NOT NULL"
            )
            rows = await cur.fetchall()
            assert rows, "fixture DB unexpectedly has no encrypted messages"
            for (payload,) in rows:
                assert not bytes(payload).startswith(STORAGE_V2_MAGIC)
            cur = await db.execute(
                "SELECT value FROM _meta WHERE key = 'storage_salt'"
            )
            assert await cur.fetchone() is None
            cur = await db.execute(
                "SELECT value FROM _meta WHERE key = 'storage_format'"
            )
            assert await cur.fetchone() is None

    def test_manifest_records_real_wheel(self):
        assert "0.9.4.2" in MANIFEST["generated_by"]


# ---------------------------------------------------------------------------
# Path 1 — identity open (keys.load_keys)
# ---------------------------------------------------------------------------

class TestIdentityOpen:
    def test_headless_load_with_passphrase(self, golden_cfg):
        from ironmesh.keys import load_keys

        k = load_keys(str(golden_cfg / "keys.json"), passphrase=PP)
        assert (base64.b64encode(k.ed25519_public).decode()
                == MANIFEST["identity"]["ed25519_public_b64"])
        assert k.get_fingerprint() == MANIFEST["identity"]["fingerprint"]
        # 0.9.4.2 wrote the v3 master-seed envelope — the X25519 subkey must
        # come back populated, not fall through to the legacy derivation.
        assert k.get_x25519_public() is not None
        assert k.get_x25519_secret() is not None

    def test_wrong_passphrase_raises(self, golden_cfg):
        from ironmesh.keys import load_keys

        with pytest.raises(Exception):
            load_keys(str(golden_cfg / "keys.json"), passphrase="not-the-pass")

    def test_encrypted_without_passphrase_raises(self, golden_cfg):
        from ironmesh.keys import load_keys

        with pytest.raises(ValueError, match="(?i)encrypted"):
            load_keys(str(golden_cfg / "keys.json"))


# ---------------------------------------------------------------------------
# Path 2 + 4 + 6 — DB open + storage-key migrate + queue replay + salt re-derive
# ---------------------------------------------------------------------------

class TestDbMigrate:
    async def test_reads_real_0942_messages(self, golden_cfg):
        from ironmesh.store import MessageStore

        store = MessageStore(str(golden_cfg / "data.db"), storage_passphrase=PP)
        await store.open()
        try:
            msgs = {m["msg_id"]: m for m in await store.get_messages(limit=100)}
        finally:
            await store.close()

        for exp in MANIFEST["messages"]:
            assert exp["msg_id"] in msgs, f"missing {exp['msg_id']}"
            assert (msgs[exp["msg_id"]]["payload"]
                    == base64.b64decode(exp["payload_b64"]))

    async def test_reads_real_0942_pending_queue(self, golden_cfg):
        from ironmesh.store import MessageStore

        store = MessageStore(str(golden_cfg / "data.db"), storage_passphrase=PP)
        await store.open()
        try:
            pending = await store.get_pending_for_peer(
                MANIFEST["pending"]["peer_node_id"]
            )
        finally:
            await store.close()

        got = {p["msg_id"]: p["payload"] for p in pending}
        for item in MANIFEST["pending"]["items"]:
            assert item["msg_id"] in got, f"missing pending {item['msg_id']}"
            assert got[item["msg_id"]] == base64.b64decode(item["payload_b64"])

    async def test_first_open_upgrades_format_and_introduces_salt(self, golden_cfg):
        from ironmesh.store import STORAGE_FORMAT_AEAD_V2, STORAGE_V2_MAGIC, MessageStore

        db = str(golden_cfg / "data.db")
        store = MessageStore(db, storage_passphrase=PP)
        await store.open()
        await store.close()

        async with aiosqlite.connect(db) as d:
            fmt = await (await d.execute(
                "SELECT value FROM _meta WHERE key = 'storage_format'"
            )).fetchone()
            salt = await (await d.execute(
                "SELECT value FROM _meta WHERE key = 'storage_salt'"
            )).fetchone()
            # every previously-legacy payload is now prefixed
            cur = await d.execute(
                "SELECT payload FROM messages WHERE payload IS NOT NULL"
            )
            rows = await cur.fetchall()

        assert fmt is not None and fmt[0] == STORAGE_FORMAT_AEAD_V2
        assert salt is not None                      # 0.9.4.2 had no salt
        assert all(bytes(p).startswith(STORAGE_V2_MAGIC) for (p,) in rows)

    async def test_reopen_after_migration_round_trips(self, golden_cfg):
        from ironmesh.store import MessageStore

        db = str(golden_cfg / "data.db")
        store1 = MessageStore(db, storage_passphrase=PP)
        await store1.open()
        await store1.close()

        store2 = MessageStore(db, storage_passphrase=PP)
        await store2.open()
        try:
            msgs = {m["msg_id"]: m for m in await store2.get_messages(limit=100)}
        finally:
            await store2.close()
        first = MANIFEST["messages"][0]
        assert msgs[first["msg_id"]]["payload"] == base64.b64decode(first["payload_b64"])

    async def test_wrong_passphrase_does_not_destroy_legacy_rows(self, golden_cfg):
        """A first open under the wrong passphrase must leave the real 0.9.4.2
        payloads byte-untouched (and unstamped), so a later correct open still
        migrates them — the same guarantee test_storage_kdf.py asserts against a
        synthesized DB, here against the real artifact."""
        from ironmesh.store import STORAGE_V2_MAGIC, MessageStore

        db = str(golden_cfg / "data.db")
        wrong = MessageStore(db, storage_passphrase="not-the-passphrase")
        await wrong.open()
        await wrong.close()

        async with aiosqlite.connect(db) as d:
            cur = await d.execute(
                "SELECT payload FROM messages WHERE payload IS NOT NULL"
            )
            rows = await cur.fetchall()
        assert all(not bytes(p).startswith(STORAGE_V2_MAGIC) for (p,) in rows)

        good = MessageStore(db, storage_passphrase=PP)
        await good.open()
        try:
            msgs = {m["msg_id"]: m for m in await good.get_messages(limit=100)}
        finally:
            await good.close()
        first = MANIFEST["messages"][0]
        assert msgs[first["msg_id"]]["payload"] == base64.b64decode(first["payload_b64"])


# ---------------------------------------------------------------------------
# Path 3 — pinned-peer load + MAC (TrustStore) — the TOFU bug surface
# ---------------------------------------------------------------------------

class TestTrustStoreLoad:
    def _agent_key(self, golden_cfg):
        from ironmesh.keys import load_keys
        k = load_keys(str(golden_cfg / "keys.json"), passphrase=PP)
        return k.ed25519_secret[:32]

    def test_pinned_peers_load_and_mac_verifies(self, golden_cfg):
        from ironmesh.trust import TrustStore

        ts = TrustStore(agent_key=self._agent_key(golden_cfg),
                        path=str(golden_cfg / "known_peers.json"))
        # MAC verified against the real 0.9.4.2 envelope -> not latched.
        assert ts._readonly_due_to_mac_failure is False
        peers = ts.list_peers()
        assert len(peers) == len(MANIFEST["peers"])
        for exp in MANIFEST["peers"]:
            assert ts.get_peer(exp["node_id"]) is not None

    def test_wrong_agent_key_latches_readonly_not_wipe(self, golden_cfg):
        """The v0.8.5.6 wipe class: a wrong agent key must fail the MAC, load
        zero peers, and latch read-only — NOT accept a write that flattens the
        on-disk file."""
        from ironmesh.trust import TrustStore

        ts = TrustStore(agent_key=b"\x11" * 32,
                        path=str(golden_cfg / "known_peers.json"))
        assert ts.list_peers() == []
        assert ts._readonly_due_to_mac_failure is True


# ---------------------------------------------------------------------------
# Path 5 — audit chain-verify, headless AND interactive, across the boundary
# ---------------------------------------------------------------------------

class TestAuditVerify:
    def test_headless_explicit_passphrase(self, golden_cfg, monkeypatch):
        from ironmesh.audit import verify_chain

        _no_tty(monkeypatch)
        ok, entries, first_bad = verify_chain(
            str(golden_cfg / "audit.log"),
            keys_path=str(golden_cfg / "keys.json"),
            keys_passphrase=PP,
        )
        assert ok is True
        assert entries == MANIFEST["audit_entry_count"]
        assert first_bad is None

    def test_headless_env_passphrase(self, golden_cfg, monkeypatch):
        from ironmesh.audit import verify_chain

        _no_tty(monkeypatch)
        monkeypatch.setenv("IRONMESH_KEYS_PASSPHRASE", PP)
        ok, entries, _ = verify_chain(
            str(golden_cfg / "audit.log"),
            keys_path=str(golden_cfg / "keys.json"),
        )
        assert ok is True
        assert entries == MANIFEST["audit_entry_count"]

    def test_headless_no_passphrase_raises_not_hangs(self, golden_cfg, monkeypatch):
        """Doctor-hang regression against a REAL 0.9.4.2 encrypted key file:
        with no passphrase and no TTY, resolution must raise an actionable
        error rather than block on a hidden getpass."""
        import getpass as getpass_mod

        from ironmesh.audit import verify_chain

        _no_tty(monkeypatch)
        _clear_pp_env(monkeypatch)
        monkeypatch.setattr(
            getpass_mod, "getpass",
            lambda prompt="": pytest.fail("getpass called in a headless run"),
        )
        with pytest.raises(ValueError, match="headless"):
            verify_chain(str(golden_cfg / "audit.log"),
                         keys_path=str(golden_cfg / "keys.json"))

    def test_interactive_getpass_resolves(self, golden_cfg, monkeypatch):
        import getpass as getpass_mod

        from ironmesh.audit import verify_chain

        _clear_pp_env(monkeypatch)
        monkeypatch.setattr("ironmesh.cli_output.stdin_is_interactive",
                            lambda: True)
        monkeypatch.setattr(getpass_mod, "getpass", lambda prompt="": PP)
        ok, entries, _ = verify_chain(str(golden_cfg / "audit.log"),
                                      keys_path=str(golden_cfg / "keys.json"))
        assert ok is True
        assert entries == MANIFEST["audit_entry_count"]

    async def test_tampered_entry_is_detected(self, golden_cfg):
        """Flipping a byte in the real 0.9.4.2 chain must be caught by HEAD's
        verifier — proves cross-version verification is genuine, not vacuous."""
        from ironmesh.audit import verify_chain

        log = golden_cfg / "audit.log"
        data = log.read_bytes()
        # Corrupt a byte in the middle of the file (inside an entry, not the
        # trailing newline).
        idx = len(data) // 2
        tampered = bytearray(data)
        tampered[idx] ^= 0x20
        log.write_bytes(bytes(tampered))

        ok, _entries, first_bad = verify_chain(
            str(log), keys_path=str(golden_cfg / "keys.json"),
            keys_passphrase=PP,
        )
        assert ok is False
        assert first_bad is not None


# ---------------------------------------------------------------------------
# Doctor — a real headless `ironmesh doctor` against a REAL 0.9.4.2 node's state
# ---------------------------------------------------------------------------

_DOCTOR_CMD = ("import sys; sys.argv = ['ironmesh', 'doctor']; "
               "from ironmesh.cli import main; raise SystemExit(main())")


def _run_doctor(home, extra_env=None, timeout=120):
    """Run doctor in a genuinely headless subprocess (stdin not a tty). The
    timeout IS the regression assertion — the pre-fix code froze forever with
    an existing audit log present."""
    env = {k: v for k, v in os.environ.items()
           if k not in ("IRONMESH_PASSPHRASE", "IRONMESH_KEYS_PASSPHRASE")}
    env["HOME"] = str(home)
    env["USERPROFILE"] = str(home)
    env["PYTHONPATH"] = str(Path(ironmesh.__file__).resolve().parent.parent)
    env["PYTHONUNBUFFERED"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"
    if extra_env:
        env.update(extra_env)
    return subprocess.run(
        [sys.executable, "-c", _DOCTOR_CMD],
        stdin=subprocess.DEVNULL, capture_output=True, encoding="utf-8",
        env=env, timeout=timeout,
    )


class TestDoctorOnReal0942State:
    def test_headless_resolvable_verifies_chain_without_prompt(self, golden_cfg):
        home = golden_cfg.parent
        res = _run_doctor(home, extra_env={"IRONMESH_KEYS_PASSPHRASE": PP})
        combined = res.stdout + res.stderr
        n = MANIFEST["audit_entry_count"]
        assert f"chain verifies clean ({n} entries)" in combined, combined
        assert "Identity key passphrase" not in combined  # never prompted

    def test_headless_unresolvable_errors_not_hangs(self, golden_cfg):
        home = golden_cfg.parent
        res = _run_doctor(home)  # no passphrase available
        combined = res.stdout + res.stderr
        assert res.returncode != 0
        assert "Identity key passphrase" not in combined  # never prompted
